#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-bootstrap
# BEFORE: datastore dispatcher

. /etc/rc.subr

bootstrap_start()
{
	# Bring up loopback interface and remount rootfs read-write
	# so datastore and dispatcher can start
	/sbin/ifconfig lo0 inet 127.0.0.1 netmask 255.0.0.0 up
	/sbin/mount -uw /
	
	# Invoking "/etc/rc.d/cleanvar" manually before the dispatcher starts
	/usr/sbin/service cleanvar onestart
	/usr/sbin/service ldconfig start
	# If there are update-related scripts, run themm, clean up, and reboot
	if [ -d /update-scripts ]; then
	    if [ -f /update-scripts/order ]; then
		cat /update-scripts/order | while read name
		do
		    sh -x /update-scripts/${name}
		done
	    else
		# Just run them alphabetically
		for name in /update-scripts/*
		do
		    sh -x ${name}
		done
	    fi
	    rm -rf /update-scripts
	    read -p "Remove this when you know it works " foo
	    reboot
	fi
}

name="ix-bootstrap"
start_cmd='bootstrap_start'
stop_cmd=':'
status_cmd=':'

load_rc_config $name
run_rc_command $*
