# $FreeBSD$

PORTNAME=	dockerfile-parse
PORTVERSION=	0.0.5
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jceel@FreeBSD.org
COMMENT=	Python library for Dockerfile manipulation.

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
