#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: clid
# REQUIRE: datastore dispatcher

. /etc/rc.subr

name="clid"
rcvar="clid_enable"
pidfile="/var/run/clid.pid"
command="/usr/sbin/daemon"
start_precmd="prestart"

prestart()
{
    rc_flags="-P ${pidfile} -f -r /usr/local/sbin/crash-wrapper /usr/local/sbin/clid ${rc_flags}"
}

load_rc_config $name
run_rc_command $*
